#!/bin/sh

xrandr --dpi 96         # Set DPI. User may want to use a larger number for larger screens.
setbg &                 # Set the background with the `setbg` script
                        # Use Xresources colors/settings on startup
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

autostart="mpd xcompmgr dunst unclutter pipewire remaps"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
